
project_id = "thpsoempfyxnjhaflyha"

[functions.idea-analysis]
verify_jwt = false

[functions.update-subscription]
verify_jwt = false

[functions.joinWaitlist]
verify_jwt = true

[functions.join-anonymous-waitlist]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-usage-status]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.analyze-market-with-scoring]
verify_jwt = false

[functions.generate-features]
verify_jwt = false

[functions.generate-validation-plan]
verify_jwt = false
