
import { toast } from '@/components/ui/sonner';
import { IdeaData } from '@/lib/types';

export function useCopySummary() {
  const copySummaryToClipboard = (data: IdeaData) => {
    const formattedCompetitors = data.competitors.map(comp => 
      `- ${comp.name} (${comp.website}): ${comp.description}`
    ).join('\n');
    
    const marketGapsAnalysis = data.marketGapAnalysis 
      ? `\n\nAI-Identified Market Gaps:\n${data.marketGapAnalysis.marketGaps.map(gap => `- ${gap}`).join('\n')}\n\nAI-Suggested Positioning:\n${data.marketGapAnalysis.positioningSuggestions.map(suggestion => `- ${suggestion}`).join('\n')}`
      : '';
    
    const summary = `
# IDEA SUMMARY

## Core Idea
${data.idea}

## Competitors
${formattedCompetitors}

## Market Gaps and Differentiation
${data.marketGaps}${marketGapsAnalysis}

## Validation Plan
${data.validationPlan}

Generated by TalonIQ
`;
    
    navigator.clipboard.writeText(summary).then(() => {
      toast.success('Summary copied to clipboard!');
    }).catch(() => {
      toast.error('Failed to copy summary');
    });
  };

  return { copySummaryToClipboard };
}
