// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thpsoempfyxnjhaflyha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocHNvZW1wZnl4bmpoYWZseWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTgxNTMsImV4cCI6MjA2MTg5NDE1M30.pfCcPY5ZxbgUi5zPJkRiWyZ2-FB6IgXlx9MtJ-4dFuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);